# Generated by Django 4.0.4 on 2022-04-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('abstract', models.CharField(max_length=700)),
                ('authors', models.CharField(max_length=100)),
                ('real_url', models.CharField(max_length=100)),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50)),
                ('is_white', models.BooleanField(default=True)),
            ],
        ),
    ]
