# Generated by Django 4.0.4 on 2022-04-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webFilter', '0002_alter_article_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(),
        ),
    ]
