# Generated by Django 4.0.4 on 2023-03-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webFilter', '0004_alter_article_title_text_alter_word_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.CharField(max_length=400),
        ),
    ]
